// Generated by CoffeeScript 1.3.3
(function() {
  var app, client, host, io, io_socket, net, port, sensor_data, server;

  app = require('express')();

  net = require('net');

  host = '10.132.16.12';

  port = 2000;

  io_socket = null;

  sensor_data = {};

  client = net.connect({
    port: port,
    host: host
  }, function() {
    return client.write('world!\r\n');
  });

  client.on('data', function(data) {
    sensor_data = data.toString();
    if (io_socket != null) {
      io.sockets.emit('status', sensor_data);
    }
    return client.end();
  });

  client.on('end', function() {
    return console.log('client disconnected');
  });

  client.on('error', function() {
    return console.log('sensor connection error');
  });

  server = require('http').createServer(app);

  io = require('socket.io').listen(server);

  server.listen(3000);

  app.get('/', function(req, res) {
    return res.sendfile(__dirname + '/views/index.html');
  });

  io.sockets.on('connection', function(socket) {
    io_socket = socket;
    io_socket.emit('status', sensor_data);
    return io_socket.on('eror', function(data) {
      console.log('error');
      return console.log(data);
    });
  });

}).call(this);
